# Generated by Django 3.1.6 on 2021-02-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='ram',
            field=models.CharField(max_length=255, verbose_name='Оперативная память'),
            preserve_default=False,
        ),
    ]
